#pragma once

// Core
#include <stratforge/analytics/extended_metrics.hpp>
#include <stratforge/core/line.hpp>
#include <stratforge/core/line_series.hpp>
#include <stratforge/core/params.hpp>
#include <stratforge/core/period_validate.hpp>

// Data
#include <stratforge/data/timeframe.hpp>
#include <stratforge/data/data_feed.hpp>
#include <stratforge/data/csv_data.hpp>
#include <stratforge/data/resampler.hpp>
#include <stratforge/data/replay.hpp>

// Broker
#include <stratforge/broker/order.hpp>
#include <stratforge/broker/commission.hpp>
#include <stratforge/broker/position.hpp>
#include <stratforge/broker/trade.hpp>
#include <stratforge/broker/broker.hpp>
#include <stratforge/broker/sizer.hpp>

// Strategy
#include <stratforge/strategy/signal.hpp>
#include <stratforge/strategy/strategy.hpp>

// Indicators
#include <stratforge/indicators/accum.hpp>
#include <stratforge/indicators/candlestick.hpp>
#include <stratforge/indicators/adaptive.hpp>
#include <stratforge/indicators/average.hpp>
#include <stratforge/indicators/awesomeoscillator.hpp>
#include <stratforge/indicators/bollinger.hpp>
#include <stratforge/indicators/bollingerpct.hpp>
#include <stratforge/indicators/atr.hpp>
#include <stratforge/indicators/aroon.hpp>
#include <stratforge/indicators/indicator.hpp>
#include <stratforge/indicators/cci.hpp>
#include <stratforge/indicators/crossover.hpp>
#include <stratforge/indicators/dema.hpp>
#include <stratforge/indicators/downday.hpp>
#include <stratforge/indicators/downmove.hpp>
#include <stratforge/indicators/directionalmovement.hpp>
#include <stratforge/indicators/dma.hpp>
#include <stratforge/indicators/dpo.hpp>
#include <stratforge/indicators/dv2.hpp>
#include <stratforge/indicators/ema.hpp>
#include <stratforge/indicators/exponentialsmoothing.hpp>
#include <stratforge/indicators/heikinashi.hpp>
#include <stratforge/indicators/hadelta.hpp>
#include <stratforge/indicators/highest.hpp>
#include <stratforge/indicators/hma.hpp>
#include <stratforge/indicators/hurst.hpp>
#include <stratforge/indicators/ichimoku.hpp>
#include <stratforge/indicators/kama.hpp>
#include <stratforge/indicators/kst.hpp>
#include <stratforge/indicators/laguerre.hpp>
#include <stratforge/indicators/lowest.hpp>
#include <stratforge/indicators/macd.hpp>
#include <stratforge/indicators/meandeviation.hpp>
#include <stratforge/indicators/momentum.hpp>
#include <stratforge/indicators/obv.hpp>
#include <stratforge/indicators/ols.hpp>
#include <stratforge/indicators/envelope.hpp>
#include <stratforge/indicators/findindex.hpp>
#include <stratforge/indicators/oscillator.hpp>
#include <stratforge/indicators/oscillator_extra.hpp>
#include <stratforge/indicators/logicaln.hpp>
#include <stratforge/indicators/statistics.hpp>
#include <stratforge/indicators/percentchange.hpp>
#include <stratforge/indicators/pctrank.hpp>
#include <stratforge/indicators/pattern.hpp>
#include <stratforge/indicators/periodn.hpp>
#include <stratforge/indicators/pivotpoint.hpp>
#include <stratforge/indicators/prettygoodoscillator.hpp>
#include <stratforge/indicators/psar.hpp>
#include <stratforge/indicators/rsi.hpp>
#include <stratforge/indicators/sma.hpp>
#include <stratforge/indicators/smma.hpp>
#include <stratforge/indicators/stddev.hpp>
#include <stratforge/indicators/stochastic.hpp>
#include <stratforge/indicators/sumn.hpp>
#include <stratforge/indicators/tema.hpp>
#include <stratforge/indicators/tsi.hpp>
#include <stratforge/indicators/trix.hpp>
#include <stratforge/indicators/trend.hpp>
#include <stratforge/indicators/truehigh.hpp>
#include <stratforge/indicators/truelow.hpp>
#include <stratforge/indicators/truerange.hpp>
#include <stratforge/indicators/ultimateoscillator.hpp>
#include <stratforge/indicators/upday.hpp>
#include <stratforge/indicators/upmove.hpp>
#include <stratforge/indicators/volume.hpp>
#include <stratforge/indicators/volatility.hpp>
#include <stratforge/indicators/vortex.hpp>
#include <stratforge/indicators/williams.hpp>
#include <stratforge/indicators/wma.hpp>
#include <stratforge/indicators/weightedaverage.hpp>
#include <stratforge/indicators/zerolag.hpp>
#include <stratforge/indicators/zlema.hpp>

// Analyzers
#include <stratforge/analyzers/analyzer.hpp>
#include <stratforge/analyzers/sharpe_ratio.hpp>
#include <stratforge/analyzers/drawdown.hpp>
#include <stratforge/analyzers/trade_analyzer.hpp>
#include <stratforge/analyzers/returns.hpp>

// Observers
#include <stratforge/observers/observer.hpp>
#include <stratforge/observers/buy_sell.hpp>
#include <stratforge/observers/cash_value.hpp>
#include <stratforge/observers/value.hpp>

// Engine
#include <stratforge/engine/cerebro.hpp>
#include <stratforge/engine/optimizer.hpp>
