// LLM-Generated Strategy: MACD with Trailing Stop
// Prompt: "Create a stratforge:: MACD trend strategy that uses trailing stop-loss,
//          buy when MACD crosses signal, trail stop by 1.5% below highest price"
// Generated by: Claude Sonnet 4.5
// Date: 2026-04-21

#include <stratforge/analyzers/sharpe_ratio.hpp>
#include <stratforge/analyzers/trade_analyzer.hpp>
#include <stratforge/data/csv_data.hpp>
#include <stratforge/engine/cerebro.hpp>
#include <stratforge/indicators/macd.hpp>
#include <stratforge/strategy/strategy.hpp>

#include <algorithm>
#include <filesystem>
#include <iostream>
#include <memory>

namespace {

std::string source_path(const std::string& relative) {
    return (std::filesystem::path(SF_SOURCE_DIR) / relative).string();
}

class MACD_Trailing_Stop : public stratforge::Strategy {
public:
    void init() override {
        macd_ = std::make_unique<stratforge::MACD>(data().close(), 12, 26, 9);
        std::cout << "Initialized MACD(12,26,9) with 1.5% trailing stop\n";
    }

    void next() override {
        if (macd_->macd().size() == 0 || macd_->signal().size() == 0) {
            return;
        }

        const double macd_line = macd_->macd()[0];
        const double signal_line = macd_->signal()[0];
        const double current_price = data().close()[0];

        // Track highest price since entry for trailing stop
        if (position().size > 0) {
            highest_since_entry_ = std::max(highest_since_entry_, current_price);

            // Calculate trailing stop price (1.5% below highest)
            const double trailing_stop = highest_since_entry_ * 0.985;

            // Exit if price hits trailing stop
            if (current_price <= trailing_stop) {
                (void)close();
                std::cout << "TRAILING STOP hit at " << current_price
                          << " (highest was " << highest_since_entry_ << ")\n";
                highest_since_entry_ = 0.0;
                return;
            }
        }

        // Entry: MACD crosses above signal (bullish)
        if (!position().size && macd_line > signal_line && macd_->histogram()[0] > 0) {
            (void)buy(75.0);
            highest_since_entry_ = current_price;

            std::cout << "BUY at ~" << current_price
                      << " (MACD=" << macd_line << ", Signal=" << signal_line << ")\n";
        }
        // Exit: MACD crosses below signal (bearish)
        else if (position().size > 0 && macd_line < signal_line) {
            (void)close();
            std::cout << "SELL (bearish signal) at ~" << current_price << "\n";
            highest_since_entry_ = 0.0;
        }
    }

private:
    std::unique_ptr<stratforge::MACD> macd_;
    double highest_since_entry_ = 0.0;
};

} // namespace

int main() {
    std::cout << "=== LLM-Generated Strategy: MACD with Trailing Stop ===\n\n";

    stratforge::Cerebro cerebro;

    auto feed = std::make_unique<stratforge::CsvData>(stratforge::CsvData::Params{
        .filename = source_path("tools/golden_extract/datas/2006-day-001.txt"),
        .columns = {},
        .date_format = "%Y-%m-%d",
        .separator = ',',
        .has_headers = true,
        .fromdate = std::nullopt,
        .todate = std::nullopt,
    });

    if (!feed->load()) {
        std::cerr << "Failed to load data\n";
        return 1;
    }

    std::cout << "Loaded " << feed->size() << " bars\n\n";

    cerebro.add_data(std::move(feed));
    cerebro.add_strategy<MACD_Trailing_Stop>();

    auto& trade_analyzer = cerebro.add_analyzer<stratforge::TradeAnalyzer>();
    auto& sharpe = cerebro.add_analyzer<stratforge::SharpeRatio>();

    cerebro.set_cash(10000.0);
    cerebro.set_commission(stratforge::CommissionInfo{.commission = 0.001});

    const double starting_cash = cerebro.broker().cash();
    std::cout << "Starting cash: $" << starting_cash << "\n\n";

    cerebro.run();

    const double final_cash = cerebro.broker().cash();
    const double pnl = final_cash - starting_cash;
    const double return_pct = (pnl / starting_cash) * 100.0;

    std::cout << "\n=== Results ===\n";
    std::cout << "Final cash: $" << final_cash << "\n";
    std::cout << "Return: " << return_pct << "%\n";

    const auto& trades = trade_analyzer.get_analysis();
    std::cout << "\nTrade Analysis:\n";
    std::cout << "  Total trades: " << trades.total.total << "\n";
    std::cout << "  Won: " << trades.won.total << " | Lost: " << trades.lost.total << "\n";

    if (trades.total.total > 0) {
        std::cout << "  Win rate: "
                  << (100.0 * trades.won.total / trades.total.total) << "%\n";
        std::cout << "  Total P&L: $" << trades.pnl.net.total << "\n";
    }

    const auto& sharpe_analysis = sharpe.get_analysis();
    std::cout << "\nRisk Metrics:\n";
    std::cout << "  Sharpe Ratio: " << sharpe_analysis.sharperatio << "\n";

    std::cout << "\n=== LLM Generation Test: PASS ===\n";
    return 0;
}
