// LLM-Generated Strategy: RSI with Stop-Loss and Take-Profit
// Prompt: "Create a stratforge:: strategy that buys when RSI(14) < 30,
//          sells when RSI > 70, with 3% stop-loss and 5% take-profit"
// Generated by: Claude Sonnet 4.5
// Date: 2026-04-21

#include <stratforge/analyzers/drawdown.hpp>
#include <stratforge/analyzers/trade_analyzer.hpp>
#include <stratforge/data/csv_data.hpp>
#include <stratforge/engine/cerebro.hpp>
#include <stratforge/indicators/rsi.hpp>
#include <stratforge/strategy/strategy.hpp>

#include <filesystem>
#include <iostream>
#include <memory>

namespace {

std::string source_path(const std::string& relative) {
    return (std::filesystem::path(SF_SOURCE_DIR) / relative).string();
}

class RSI_With_Stop_And_Target : public stratforge::Strategy {
public:
    void init() override {
        rsi_ = std::make_unique<stratforge::RSI>(data().close(), 14);
        std::cout << "Initialized RSI(14) strategy with stop-loss and take-profit\n";
        std::cout << "  Entry: RSI < 30\n";
        std::cout << "  Exit: RSI > 70 OR 3% stop-loss OR 5% take-profit\n";
    }

    void next() override {
        if (rsi_->line().size() == 0) {
            return;
        }

        const double rsi_value = rsi_->line()[0];
        const double current_price = data().close()[0];

        // Entry: Oversold condition (RSI < 30)
        if (!position().size && rsi_value < 30.0) {
            const double entry_price = current_price;
            const double stop_price = entry_price * 0.97;   // 3% stop-loss
            const double target_price = entry_price * 1.05; // 5% take-profit

            // Place market buy
            (void)buy(100.0);

            // Place stop-loss
            stop_order_id_ = sell(100.0, stop_price, stratforge::OrderType::Stop);

            // Place take-profit limit
            target_order_id_ = sell(100.0, target_price, stratforge::OrderType::Limit);

            entry_price_ = entry_price;

            std::cout << "BUY at ~" << entry_price
                      << " (RSI=" << rsi_value << ")"
                      << " | Stop=" << stop_price
                      << " | Target=" << target_price << "\n";
        }
        // Exit: Overbought condition (RSI > 70)
        else if (position().size > 0 && rsi_value > 70.0) {
            // Cancel pending orders
            if (stop_order_id_ != 0) {
                (void)cancel(stop_order_id_);
                stop_order_id_ = 0;
            }
            if (target_order_id_ != 0) {
                (void)cancel(target_order_id_);
                target_order_id_ = 0;
            }

            (void)close();
            std::cout << "SELL (overbought) at ~" << current_price
                      << " (RSI=" << rsi_value << ")\n";
        }
    }

    void notify_order(const stratforge::Order& order) override {
        if (order.status == stratforge::OrderStatus::Completed) {
            if (order.id == stop_order_id_) {
                std::cout << "  -> STOP-LOSS executed at " << order.executed_price << "\n";
                stop_order_id_ = 0;
                if (target_order_id_ != 0) {
                    (void)cancel(target_order_id_);
                    target_order_id_ = 0;
                }
            } else if (order.id == target_order_id_) {
                std::cout << "  -> TAKE-PROFIT executed at " << order.executed_price << "\n";
                target_order_id_ = 0;
                if (stop_order_id_ != 0) {
                    (void)cancel(stop_order_id_);
                    stop_order_id_ = 0;
                }
            }
        }
    }

private:
    std::unique_ptr<stratforge::RSI> rsi_;
    std::size_t stop_order_id_ = 0;
    std::size_t target_order_id_ = 0;
    double entry_price_ = 0.0;
};

} // namespace

int main() {
    std::cout << "=== LLM-Generated Strategy: RSI with Stop-Loss and Take-Profit ===\n\n";

    stratforge::Cerebro cerebro;

    auto feed = std::make_unique<stratforge::CsvData>(stratforge::CsvData::Params{
        .filename = source_path("tools/golden_extract/datas/2006-day-001.txt"),
        .columns = {},
        .date_format = "%Y-%m-%d",
        .separator = ',',
        .has_headers = true,
        .fromdate = std::nullopt,
        .todate = std::nullopt,
    });

    if (!feed->load()) {
        std::cerr << "Failed to load data\n";
        return 1;
    }

    std::cout << "Loaded " << feed->size() << " bars\n\n";

    cerebro.add_data(std::move(feed));
    cerebro.add_strategy<RSI_With_Stop_And_Target>();

    auto& trade_analyzer = cerebro.add_analyzer<stratforge::TradeAnalyzer>();
    auto& drawdown = cerebro.add_analyzer<stratforge::Drawdown>();

    cerebro.set_cash(10000.0);
    cerebro.set_commission(stratforge::CommissionInfo{.commission = 0.001});

    const double starting_cash = cerebro.broker().cash();
    std::cout << "Starting cash: $" << starting_cash << "\n\n";

    cerebro.run();

    const double final_cash = cerebro.broker().cash();
    const double pnl = final_cash - starting_cash;

    std::cout << "\n=== Results ===\n";
    std::cout << "Final cash: $" << final_cash << "\n";
    std::cout << "P&L: $" << pnl << "\n";

    const auto& trades = trade_analyzer.get_analysis();
    std::cout << "\nTrade Analysis:\n";
    std::cout << "  Total: " << trades.total.total << "\n";
    std::cout << "  Won: " << trades.won.total << " | Lost: " << trades.lost.total << "\n";

    if (trades.total.total > 0) {
        std::cout << "  Win rate: " << (100.0 * trades.won.total / trades.total.total) << "%\n";
    }

    const auto& dd = drawdown.get_analysis();
    std::cout << "\nDrawdown:\n";
    std::cout << "  Max: " << dd.max.drawdown << "%\n";

    std::cout << "\n=== LLM Generation Test: PASS ===\n";
    return 0;
}
