// LLM-Generated Strategy: SMA Crossover with Stop-Loss
// Prompt: "Create a C++ strategy using stratforge:: that implements an SMA crossover
//          system with SMA(10)/SMA(30), 2% stop-loss, 50 share position size"
// Generated by: Claude Sonnet 4.5
// Date: 2026-04-21

#include <stratforge/analyzers/trade_analyzer.hpp>
#include <stratforge/data/csv_data.hpp>
#include <stratforge/engine/cerebro.hpp>
#include <stratforge/indicators/sma.hpp>
#include <stratforge/strategy/strategy.hpp>

#include <filesystem>
#include <iostream>
#include <memory>

namespace {

std::string source_path(const std::string& relative) {
    return (std::filesystem::path(SF_SOURCE_DIR) / relative).string();
}

class SMA_Crossover_With_Stop : public stratforge::Strategy {
public:
    void init() override {
        sma_fast_ = std::make_unique<stratforge::SMA>(data().close(), 10);
        sma_slow_ = std::make_unique<stratforge::SMA>(data().close(), 30);
        std::cout << "Initialized SMA Crossover with 2% stop-loss\n";
    }

    void next() override {
        // Wait for indicators to have valid values
        if (sma_fast_->line().size() == 0 || sma_slow_->line().size() == 0) {
            return;
        }

        const double fast_sma = sma_fast_->line()[0];
        const double slow_sma = sma_slow_->line()[0];
        const double current_price = data().close()[0];

        // Entry: Fast crosses above slow
        if (!position().size && fast_sma > slow_sma) {
            const double entry_price = current_price;
            const double stop_price = entry_price * 0.98; // 2% stop-loss

            // Place market buy order
            (void)buy(50.0);

            // Place stop-loss order
            stop_order_id_ = sell(50.0, stop_price, stratforge::OrderType::Stop);

            entry_price_ = entry_price;

            std::cout << "BUY: 50 shares at ~" << entry_price
                      << ", stop at " << stop_price << "\n";
        }
        // Exit: Fast crosses below slow
        else if (position().size > 0 && fast_sma < slow_sma) {
            // Cancel stop-loss if still pending
            if (stop_order_id_ != 0) {
                (void)cancel(stop_order_id_);
                stop_order_id_ = 0;
            }

            (void)close();
            std::cout << "SELL: Close position at ~" << current_price << "\n";
        }
    }

    void notify_order(const stratforge::Order& order) override {
        // Track when stop-loss is hit
        if (order.id == stop_order_id_ && order.status == stratforge::OrderStatus::Completed) {
            std::cout << "STOP-LOSS hit at " << order.executed_price << "\n";
            stop_order_id_ = 0;
        }
    }

private:
    std::unique_ptr<stratforge::SMA> sma_fast_;
    std::unique_ptr<stratforge::SMA> sma_slow_;
    std::size_t stop_order_id_ = 0;
    double entry_price_ = 0.0;
};

} // namespace

int main() {
    std::cout << "=== LLM-Generated Strategy: SMA Crossover with Stop-Loss ===\n\n";

    stratforge::Cerebro cerebro;

    // Load data
    auto feed = std::make_unique<stratforge::CsvData>(stratforge::CsvData::Params{
        .filename = source_path("tools/golden_extract/datas/2006-day-001.txt"),
        .columns = {},
        .date_format = "%Y-%m-%d",
        .separator = ',',
        .has_headers = true,
        .fromdate = std::nullopt,
        .todate = std::nullopt,
    });

    if (!feed->load()) {
        std::cerr << "Failed to load data\n";
        return 1;
    }

    std::cout << "Loaded " << feed->size() << " bars\n\n";

    cerebro.add_data(std::move(feed));
    cerebro.add_strategy<SMA_Crossover_With_Stop>();

    auto& analyzer = cerebro.add_analyzer<stratforge::TradeAnalyzer>();

    // Broker setup
    cerebro.set_cash(10000.0);
    cerebro.set_commission(stratforge::CommissionInfo{.commission = 0.001});

    const double starting_cash = cerebro.broker().cash();
    std::cout << "Starting cash: $" << starting_cash << "\n\n";

    // Run backtest
    cerebro.run();

    // Results
    const double final_cash = cerebro.broker().cash();
    const double pnl = final_cash - starting_cash;
    const double return_pct = (pnl / starting_cash) * 100.0;

    std::cout << "\n=== Results ===\n";
    std::cout << "Final cash: $" << final_cash << "\n";
    std::cout << "P&L: $" << pnl << " (" << return_pct << "%)\n";

    const auto& trades = analyzer.get_analysis();
    std::cout << "\nTrade Analysis:\n";
    std::cout << "  Total trades: " << trades.total.total << "\n";
    std::cout << "  Won: " << trades.won.total << " | Lost: " << trades.lost.total << "\n";

    if (trades.total.total > 0) {
        const double win_rate = (100.0 * trades.won.total) / trades.total.total;
        std::cout << "  Win rate: " << win_rate << "%\n";
    }

    std::cout << "\n=== LLM Generation Test: PASS ===\n";
    return 0;
}
